### PR TITLE
Correct icons are loaded when changing the theme.

### LINKED ISSUE #14: Changing icons on theme change
**Describe the bug**

**To Reproduce**
1. Open Envoy
2. Change Theme
3. Return back to `ChatScene`
4. Enjoy.

**Expected behavior**
Icons should be shown depending on the current theme, not on what has been stored when popping the scene.
To solve the problem, one should edit the method `onRestorable` so that it again sets all theme speific icons.

This shows how it should NOT look like in light mode (Envoy was started in dark mode):
grafik

### PR DESCRIPTION
**Pull request by DieGurke**
fixes #14

### CODE REVIEW

File: client/src/main/java/envoy/client/ui/controller/ChatScene.java [hunk 1]
```diff
@@ -346,7 +346,18 @@ public void initializeData(SceneContext sceneContext, LocalDB localDB, Client cl
 	}
 
 	@Override
-	public void onRestore() { updateRemainingCharsLabel(); }
+	public void onRestore() {
+		updateRemainingCharsLabel();
+		settingsButton.setGraphic(new ImageView(IconUtil.loadIconThemeSensitive("settings", DEFAULT_ICON_SIZE)));
+		voiceButton.setGraphic(new ImageView(IconUtil.loadIconThemeSensitive("microphone", DEFAULT_ICON_SIZE)));
+		attachmentButton.setGraphic(new ImageView(IconUtil.loadIconThemeSensitive("attachment", DEFAULT_ICON_SIZE)));
+		attachmentView.setImage(DEFAULT_ATTACHMENT_VIEW_IMAGE);
```
Comment (delvh) [inline client/src/main/java/envoy/client/ui/controller/ChatScene.java:354]: There is a reason why I decided not to implement it directly, but rather open an issue: I do not know if you have noticed, but if you attach an image, this image will be previewed there rather than the `attachment_present.png`. In your current implementation, this feature will be removed again if the user opens (i.e.) the `SettingsScene` and closes it.
Furthermore, there is another issue not covered by this Fix: Look at the declaration of `DEFAULT_ATTACHMENT_VIEW_IMAGE`: It is loaded **theme sensitive**, meaning there is a different version for each theme. Hence in case of a scene change, the wrong image will be displayed.

File: client/src/main/java/envoy/client/ui/controller/ChatScene.java [hunk 2]
```diff
@@ -346,7 +346,18 @@ public void initializeData(SceneContext sceneContext, LocalDB localDB, Client cl
...
+		messageSearchButton.setGraphic(new ImageView(IconUtil.loadIconThemeSensitive("search", DEFAULT_ICON_SIZE)));
+		clientProfilePic.setImage(IconUtil.loadIconThemeSensitive("user_icon", 43));
+		chatList.setCellFactory(new ListCellFactory<>(ChatControl::new));
+		if (currentChat.getRecipient() instanceof User) recipientProfilePic.setImage(IconUtil.loadIconThemeSensitive("user_icon", 43));
```
Comment (delvh) [inline client/src/main/java/envoy/client/ui/controller/ChatScene.java:358]: For now, this'll work. It'll cause problems once we implement custom profile pics.

File: client/src/main/java/envoy/client/ui/controller/ChatScene.java [hunk 3]
```diff
@@ -346,7 +346,18 @@ public void initializeData(SceneContext sceneContext, LocalDB localDB, Client cl
...
+		else recipientProfilePic.setImage(IconUtil.loadIconThemeSensitive("group_icon", 43));
```
Comment (delvh) [inline client/src/main/java/envoy/client/ui/controller/ChatScene.java:359]: See above.

**Review by delvh — COMMENTED** [review]
In parts it does what it is supposed to but the key elements of the issue are just not  addressed...

File: client/src/main/java/envoy/client/ui/controller/ChatScene.java [hunk 4]
```diff
@@ -346,7 +346,18 @@ public void initializeData(SceneContext sceneContext, LocalDB localDB, Client cl
...
-	public void onRestore() { updateRemainingCharsLabel(); }
+	public void onRestore() {
+		updateRemainingCharsLabel();
+		settingsButton.setGraphic(new ImageView(IconUtil.loadIconThemeSensitive("settings", DEFAULT_ICON_SIZE)));
+		voiceButton.setGraphic(new ImageView(IconUtil.loadIconThemeSensitive("microphone", DEFAULT_ICON_SIZE)));
+		attachmentButton.setGraphic(new ImageView(IconUtil.loadIconThemeSensitive("attachment", DEFAULT_ICON_SIZE)));
+		attachmentView.setImage(DEFAULT_ATTACHMENT_VIEW_IMAGE);
+		messageSearchButton.setGraphic(new ImageView(IconUtil.loadIconThemeSensitive("search", DEFAULT_ICON_SIZE)));
+		clientProfilePic.setImage(IconUtil.loadIconThemeSensitive("user_icon", 43));
+		chatList.setCellFactory(new ListCellFactory<>(ChatControl::new));
```
Comment (CyB3RC0nN0R) [inline client/src/main/java/envoy/client/ui/controller/ChatScene.java:357]: `messageList` has to be reloaded as well because of the forward icon.

**Review by delvh — APPROVED** [review]
:+1: That's how it was supposed to be...

File: client/src/main/java/envoy/client/ui/controller/ChatScene.java [hunk 5]
```diff
@@ -144,6 +129,13 @@
 	@FXML
 	private HBox contactSpecificOnlineOperations;
 
+	private Chat				currentChat;
+	private FilteredList<Chat>	chats;
+	private boolean				recording;
+	private Attachment			pendingAttachment;
+	private boolean				postingPermanentlyDisabled;
+	private boolean				isCustomAttachmentImage	= false;
```
Comment (CyB3RC0nN0R) [inline client/src/main/java/envoy/client/ui/controller/ChatScene.java:137]:
```suggestion
	private boolean				isCustomAttachmentImage;
```

**Review by CyB3RC0nN0R — APPROVED** [review]

**Review by CyB3RC0nN0R — APPROVED** [review]

**Review by delvh — APPROVED** [review]
Webergebnisse, etc...
👍
